### ISSUE TITLE
Failed to compile 

### ISSUE THREAD

**Issue by ghost** [coolsee/OpenMugen#5]
[  5%] Building CXX object CMakeFiles/openmugen.dir/tokenizer.cpp.o
/home/pi/Desktop/OpenMugen/tokenizer.cpp: In member function ‘char* CTokenizer::GetPartToken()’:
/home/pi/Desktop/OpenMugen/tokenizer.cpp:343:10: error: cannot convert ‘bool’ to ‘char*’ in return
   return false;
          ^~~~~
CMakeFiles/openmugen.dir/build.make:398: fallo en las instrucciones para el objetivo 'CMakeFiles/openmugen.dir/tokenizer.cpp.o'
make[2]: *** [CMakeFiles/openmugen.dir/tokenizer.cpp.o] Error 1
CMakeFiles/Makefile2:67: fallo en las instrucciones para el objetivo 'CMakeFiles/openmugen.dir/all'
make[1]: *** [CMakeFiles/openmugen.dir/all] Error 2
Makefile:83: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

**Comment by lijinchao2007** [comment]
I copy the code from other site. long time passed, I have no idea about the error.
